### ISSUE TITLE
ImageNet HLS Model is Missing

### ISSUE THREAD

**Issue by asagot** [cornell-zhang/FracBNN#1]
You only show how to deploy the CIFAR-10 variant. Can you also add how to test with the ImageNet dataset?

**Comment by asagot** [comment]
Any plans to add the ImageNet variant that can be run on the FPGA?

**Comment by ychzhang** [comment]
Hi asagot,

Thank you for checking out our code. We're currently working on other submissions, so there is a delay on cleaning up the ImageNet accelerator. We'll clean up the code and release it probably sometime in the next month.

**Comment by asagot** [comment]
Thank you, looking for ward to seeing it.
