### ISSUE TITLE
Imagenet deployment

### ISSUE THREAD

**Issue by lloo099** [cornell-zhang/FracBNN#4]
Hi @ychzhang , could u provide imagenet version of ur francBNN? As I compiled this project, it shows invalid results. Thanks,

**Comment by ychzhang** [comment]
@lloo099 Hi, FracBNN ImageNet [accelerator](https://github.com/cornell-zhang/FracBNN/tree/main/xcel-imagenet), [model specification](https://github.com/cornell-zhang/FracBNN/blob/main/model/fracbnn_imagenet.py), and the [pretrained model](https://drive.google.com/file/d/1VyMigxNAW4qQi_uVwifhfJ8FckAxnBhB/view?usp=sharing) have all been released in this repo. For ImageNet deployment instructions and preprocessed weights or sample images, please refer to [the last part of the Readme](https://github.com/cornell-zhang/FracBNN#imagenet-accelerator).

**Comment by lloo099** [comment]
Thanks
