### ISSUE TITLE
weight dimensions in pgconv.h

### ISSUE THREAD

**Issue by chuliang007** [cornell-zhang/FracBNN#6]
Dear @ychzhang, 

Assume we use the same dimension notations in **tb.cc** for input[CHANNEL_IN][HEIGHT_IN][WIDTH_IN] and weight[CHANNEL_OUT][CHANNEL_IN][3][3]. In **pgconv.h**, CHANNEL_IN for inputs and weight input is 1. While such dimensions should be 16, 32, and 64 in resnet20_cifar (e.g., input[1][16][32][32], weight[16][16][3][3]) in layer1.0_conv). 

I am not sure whether my understanding is incorrect, and could you please provide a brief explanation of it? Thanks in advance!

**Comment by ychzhang** [comment]
Hi @chuliang007 , 

In pgconv.h, the type of input and weight arrays is **uint64**. Each 64-bit integer in the array is a result of packed 64 input channels, since the inputs and weights to a conv layer are all binary. 
If the number of input channels is less than 64, we pad zeros at the end.

**Comment by wwdxdl** [comment]
Can the author share the conversion code for the above weight packaging, thank you very much！
